name: practise
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  dio: ^5.9.0
  dartz: ^0.10.1
  data_connection_checker_tv: ^0.3.5-nullsafety
  path_provider: ^2.1.0
  cupertino_icons: ^1.0.2
  elementary: ^3.2.0
  elementary_helper: ^1.0.2
  material_color_utilities: ^0.11.1
  freezed_annotation: ^2.4.4
  state_notifier: ^1.0.0
  json_annotation: ^4.9.0
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.2.1
  badges: ^3.1.2
  dotted_line: ^3.1.0
  another_flushbar: ^1.10.29
  auto_route: ^7.9.2
  material_dialogs: ^1.1.5
  lottie: ^3.3.1
  provider: ^6.0.5
  intl: ^0.18.1
  flutter_secure_storage: ^9.2.4
  local_auth: ^2.1.8
  retrofit: ^4.6.0
  get_it: ^8.2.0
  injectable: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  auto_route_generator: ^7.3.2
  retrofit_generator: ^9.3.0
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true
  assets:
    - lib/ui/assets/task.png
    - lib/ui/assets/star.png
    - lib/ui/assets/dance_stars.json
    - lib/ui/assets/dance_stars.gif