// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOP_5DmcPG5lhPry6nL7C870B_042IH4s',
    appId: '1:370301516397:web:2b986b67ee7210fc901d64',
    messagingSenderId: '370301516397',
    projectId: 'fir-proj-9ef68',
    authDomain: 'fir-proj-9ef68.firebaseapp.com',
    storageBucket: 'fir-proj-9ef68.firebasestorage.app',
    measurementId: 'G-B8FMNEBW2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPCl_U-tLPkR51qryvDNTf5ryah0CNu_o',
    appId: '1:370301516397:android:3dbb3aa9636f04f6901d64',
    messagingSenderId: '370301516397',
    projectId: 'fir-proj-9ef68',
    storageBucket: 'fir-proj-9ef68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCysCnsXtGgUCVbRZs8ueLvMsEsHHN1YCc',
    appId: '1:370301516397:ios:b3f3dfde1cad673e901d64',
    messagingSenderId: '370301516397',
    projectId: 'fir-proj-9ef68',
    storageBucket: 'fir-proj-9ef68.firebasestorage.app',
    iosBundleId: 'com.example.testProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCysCnsXtGgUCVbRZs8ueLvMsEsHHN1YCc',
    appId: '1:370301516397:ios:b3f3dfde1cad673e901d64',
    messagingSenderId: '370301516397',
    projectId: 'fir-proj-9ef68',
    storageBucket: 'fir-proj-9ef68.firebasestorage.app',
    iosBundleId: 'com.example.testProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOP_5DmcPG5lhPry6nL7C870B_042IH4s',
    appId: '1:370301516397:web:f64e78ff3950d390901d64',
    messagingSenderId: '370301516397',
    projectId: 'fir-proj-9ef68',
    authDomain: 'fir-proj-9ef68.firebaseapp.com',
    storageBucket: 'fir-proj-9ef68.firebasestorage.app',
    measurementId: 'G-MWG3VV7R0D',
  );
}
